export enum EnemyLocation {
  SLIME_FIELDS = 'SLIME_FIELDS',
  ABANDONED_FARM = 'ABANDONED_FARM',
  RAT_CAVES = 'RAT_CAVES',
  SPIDER_NEST = 'SPIDER_NEST',
  GOBLIN_CAMP = 'GOBLIN_CAMP',
  CURSED_GRAVEYARD = 'CURSED_GRAVEYARD',
  BANDIT_HILLS = 'BANDIT_HILLS',
  TROLL_BRIDGE = 'TROLL_BRIDGE',
  DEMONIC_ALTAR = 'DEMONIC_ALTAR',
  DRAGON_PEAK = 'DRAGON_PEAK',
}
